spring:
  #shardingsphere配置
  shardingsphere:
    #配置数据源列表
    dataSource:
      #数据源集合
      names: ds0,ds1
      #配置数据源ds0
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/db0
        username: root
        password: 123456
      #配置数据源ds1
      ds1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/db1
        username: root
        password: 123456
    #配置分片规则
    sharding:
      #配置参与分片的table列表; 可以针对单个逻辑表单独配置分表策略、分库策略，也可以配置默认分库/分表策略应用给所有表
      tables:
        #配置逻辑表t_user的分片规则
        t_user:
          #逻辑表t_user有四个物理表：ds0.t_user0, ds0.t_user1, ds1.t_user0, ds1.t_user1
          actual-data-nodes: ds$->{0..1}.t_user$->{0..1}
      #配置默认分表策略
      default-table-strategy:
        #行表达式分片策略; 分片策略还可以是standard、complex、hint，详见官方文档
        inline:
          #行表达式分片的依据字段
          sharding-column: id
          #行表达式分片的算法：id为偶数路由到ds0.t_user0，id为奇数路由到ds0.t_user1
          algorithm-expression: t_user$->{id % 2}
      #配置默认分库策略
      default-database-strategy:
        inline:
          #行表达式分片的依据字段
          sharding-column: age #分库的字段
          #行表达式分片的算法：age为偶数路由到ds0，age为奇数路由到ds1
          algorithm-expression: ds$->{age % 2} #分片的算法
    props:
      sql:
        show: true
#更多配置详见ShardingSphere官方文档